### ISSUE TITLE
What is the licence of GAS?

### ISSUE THREAD

**Issue by Tyrben** [googleworkspace/apps-script-samples#172]
## Expected Behavior

Sample URL:
Description: Should read easily under which licence was invented.

## Actual Behavior
Nothing easy to find. Seems unreferenced.

## Steps to Reproduce the Problem
Search for information regarding Google Apps Script.

**Comment by sqrrrl** [comment]
Not sure which example you're referring to, but everything in this repo is Apache 2 (see top-level LICENSE)

For Apps Script itself, see https://developers.google.com/apps-script/terms for terms of service.
