### ISSUE TITLE
How to get current (opened or new) draft?

### ISSUE THREAD

**Issue by Grinnbob** [googleworkspace/apps-script-samples#174]
I need to get data from newly created draft.

This solution
var draft = GmailApp.getDrafts()[0]; // The first draft message in the drafts folder
is not relevant.

So how can I get it? Maybe there is any way to save draft and then get it in this way?

**Comment by contributorpw** [comment]
If we talk about drafts in perspective you may to use Gmail API  https://developers.google.com/gmail/api/reference/rest/v1/users.drafts/get (don't forget `format=raw`)

As for such questions in general there is the best place for ask https://groups.google.com/g/google-apps-script-community

**Comment by harshaldhone** [comment]
I don't understand your question completely but as I understood..
  `var drafts = GmailApp.getDrafts()[0]; // The first draft message in the drafts folder
    var draft=drafts.getMessage();
    console.log(draft.getBody()); ` 

in place of .getBody you can use different methods as per your need as per this [https://developers.google.com/apps-script/reference/gmail/gmail-message](this)

**Comment by sqrrrl** [comment]
This issue looks like a general question about apps script development, not the samples contained in this repository. We recommend asking such using the resources in the [support guide.](https://developers.google.com/apps-script/support)
