### ISSUE TITLE
payload not showing correctly in runtime v8

### ISSUE THREAD

**Issue by henrikbergstrom** [googleworkspace/apps-script-samples#179]
## Expected Behavior

 var parameters = {
      isValid: true,
      content: 'some string',
      timestamp: new Date()
  };
  console.log({message: 'Function Input', initialData: parameters});

I expect to see Payload with 3 values in stackdriver.

## Actual Behavior

I get one JSON string in Payload in stackdriver.

## Steps to Reproduce the Problem

1. Run script in V8

 var parameters = {
      isValid: true,
      content: 'some string',
      timestamp: new Date()
  };
  console.log({message: 'Function Input', initialData: parameters});

2. Check stackdriver payload.

https://stackoverflow.com/questions/65320700/stackdriver-logging-why-is-not-my-payload-showing-correctly-in-runtime-v8

**Comment by sqrrrl** [comment]
This issue looks like a general question about apps script development, not the samples contained in this repository. We recommend asking such using the resources in the [support guide.](https://developers.google.com/apps-script/support)
