### ISSUE TITLE
Apps Script Quickstart Google Sheet is not shared publicly

### ISSUE THREAD

**Issue by ErikLentz** [googleworkspace/apps-script-samples#187]
## Expected Behavior
On this URL, on Step 1, a sample spreadsheet is linked, but the spreadsheet is not publicly accessible. https://developers.google.com/apps-script/quickstart/forms

Sample URL: https://docs.google.com/spreadsheet/ccc?key=1HgtMSoatp1M6pQwwwQqHgZX7jZRldDbSX8VIJ468d4c&newcopy=true
Description:

## Actual Behavior
The sample spreadsheet is publicly accessible. No access request is required.

## Steps to Reproduce the Problem

1. Navigate to https://developers.google.com/apps-script/quickstart/forms
2. Click "Apps Script Quickstart: Managing responses for Google Forms" 
3. Receive an error that request needed for access

**Comment by contributorpw** [comment]
This is a 'copy link'. You can get the source file by deleting the word `copy` from the end of url `https://docs.google.com/spreadsheets/d/1HgtMSoatp1M6pQwwwQqHgZX7jZRldDbSX8VIJ468d4c`.

For main behavior you need to click `Make a copy` button

![1613702131408](https://user-images.githubusercontent.com/5027939/108449342-5b643a00-7274-11eb-948b-56ba3ce6f779.png)

**Comment by ErikLentz** [comment]
Looks like it's an org-wide security setting.
