### ISSUE TITLE
Images and formatting not appearing in the email

### ISSUE THREAD

**Issue by johnm7RDI** [googleworkspace/apps-script-samples#189]
## Expected Behavior: 

Sample URL: https://script.google.com/u/0/home/projects/1l6nr6dH8FB1WpIa-q7C0MWqzzHi3lJypVAuiOsGM5xQ38C90p0kKPtRi/edit
Description: Images or links embedded in the body of the email do not work in the actual email sent out. Is there a workaround?

**Comment by sqrrrl** [comment]
This issue looks like a general question about apps script development, not the samples contained in this repository. We recommend asking such using the resources in the [support guide.](https://developers.google.com/apps-script/support)
