### ISSUE TITLE
ReferenceError: moment is not defined 

### ISSUE THREAD

**Issue by ZenonH** [googleworkspace/apps-script-samples#197]
## Expected Behavior

Sample URL:
Description: DATEADD function generating ReferenceError: moment is not defined 

## Actual Behavior
ReferenceError: moment is not defined 

## Steps to Reproduce the Problem
function testdate(){
  /*var date = 'April 1, 2021'
  //var newDate = DATEADD(date, 'months', 3);
  var date = '2021-04-01'
  var newDate = DATEADD(date, 'months', 3);*/
  var date = new Date;
  var newDate = DATEADD(date, 'months', 3);
}

**Comment by sqrrrl** [comment]
This issue looks like a general question about apps script development, not the samples contained in this repository. We recommend asking such using the resources in the [support guide.](https://developers.google.com/apps-script/support)
