### ISSUE TITLE
UrlFetchApp Calls

### ISSUE THREAD

**Issue by mado-bohsali** [googleworkspace/apps-script-samples#214]
UrlFetchApp.fetch (POST) is being executed many times although the UrlFetchApp isn't inside a loop. It should execute only once upon user submits the whole form.

<img width="1106" alt="Screen Shot 2021-07-26 at 12 35 31 PM" src="https://user-images.githubusercontent.com/18421260/128335426-c985144f-1c16-47ad-a469-6d5dfe173743.png">

**Comment by sqrrrl** [comment]
This issue looks like a general question about apps script development, not the samples contained in this repository. We recommend asking such using the resources in the [support guide.](https://developers.google.com/apps-script/support)
