### ISSUE TITLE
Alphabetizing tabs in a sheets - ignoring case

### ISSUE THREAD

**Issue by nolafsen** [googleworkspace/apps-script-samples#220]
I've added a script to alphabetize numerous tabs within sheets including excluding the first four tabs.  Works great, except it is alphabetizing all with Capital letters first, then alphabetizing all with lower case at the end.  Any idea how to ignore case?

This is the script i am using:

function onOpen () {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var sheetNameArray = [];
  var sheets = ss.getSheets();
   
  for (var i = 0; i < sheets.length; i++) {
    sheetNameArray.push(sheets[i].getName());
  }
  
  sheetNameArray.sort();
    
  for( var j = 0; j < sheets.length; j++ ) {
    ss.setActiveSheet(ss.getSheetByName(sheetNameArray[j]));
    ss.moveActiveSheet(j + 1);
  }
  
  ["Index", "Phillies", "Eagles", "Flyers"].forEach((name,i)=>{
              ss.setActiveSheet(ss.getSheetByName(name));
              ss.moveActiveSheet(i + 1);                                                                       
        })
  }

Thank you,
Nicole

**Comment by Wethepeople20** [comment]
to solve the issue of the capital letters of the alphabet not correllating with the lower-case/non-capital letters of the alphabet used in similar scenarios, I would first try the following:
Step 1-Find the file that lists the order for "alphabetical order" function.
Step 2- Make Decisions as to whether to include other characters (other alphabet equivalents to the alphabet in the English QWERTY keyboard variation of the Alphabet, numbers, greek or math symbols) and if chosen as parts of the alphabet(s) order being edited, where in the list of symbols/letters they should be located. 
Step 3- For this simple version of the example problem, one should Re-list the library for alphabet as follows: 
   "A, a,  B, b, C, c, D, d, E, e, F, f, G,g, H, h, I, i, J, j, K, k... and so forth in that manner.
           - For more symbols to be integrated, perhaps one would list the greek alpha symbol with the symbols A and a, and the beta symbol with b, but the question there is, where in the set of letters does each fall? Does beta fall before the capital B, before the lowercase b, or after both?
             - One question to ask is whether the alphabet ends after Z and/or other included characters in the Z, z, set, or whether after Z, z you re-start the list: Z, z, (return to) top.
But for this one would need the Administrator/Superuser to approve the changes, most likely, unless the permissions were granted as a whole for changes such as this one to the developer currently doing the job.
(f)search>alphabetical order<

**Comment by sqrrrl** [comment]
This issue looks like a general question about apps script development, not the samples contained in this repository. We recommend asking such using the resources in the [support guide.](https://developers.google.com/apps-script/support)
