### ISSUE TITLE
Question:  How to import Contacts from a CSV File with APPS SCRIPT and triggerd/automatic ?

### ISSUE THREAD

**Issue by tomK90** [googleworkspace/apps-script-samples#223]
Hi,
How to import Contacts with APPS SCRIPT from a CSV File ?

Have a CSV File with Contacts that will created every day. This Contacts
sould be imported from Google Drive with a Trigger so that no interaction from User is needed.

How to do this, did not found example for Import from CSV File.
Found onyl import to google spreadsheet but this is not what I want.

I like to do Import (at contacts.google.com I can do this interativ, but sould run automated) but as APPS Script.

Thanks

TOm

**Comment by sqrrrl** [comment]
This issue looks like a general question about apps script development, not the samples contained in this repository. We recommend asking such using the resources in the [support guide.](https://developers.google.com/apps-script/support)
