### ISSUE TITLE
Google Sheet Schedule Trigger event > Wait for 5 mints > Trigger Row 1 - 200 and so on

### ISSUE THREAD

**Issue by harismateen** [googleworkspace/apps-script-samples#229]
Hi, Is there away to schedule trigger event base of range of rows? 

Example
1. Raw_1 to Raw_100 --- Trigger API ---> wait for 5 mints ---> Raw_101 to Raw_200 --- Tigger API ----etc etc

**Comment by sqrrrl** [comment]
This issue looks like a general question about apps script development, not the samples contained in this repository. We recommend asking such using the resources in the [support guide.](https://developers.google.com/apps-script/support)
