### ISSUE TITLE
Deployment complete remove within Manage deployments dialog in Apps scripts

### ISSUE THREAD

**Issue by projektorius96** [googleworkspace/apps-script-samples#236]
## Expected Behaviour

Sample URL: @https://issuetracker.google.com/issues/191993383
Description (copy-pasted): When you get too many deployments within **Manage deployments dialog, it gets too crowdy** . I am kindly requesting a feature to garbage collect i.e. to **remove unused (archived) deployments completely**, not only archiving . I assume this is important not only for me . Every programmer must stay organized. This definitely would make our life easier.

## Actual Behaviour
I've observed Apps Script API . It seems there exists a method of `Projects.deployments.delete` which AFAIK would enable archived deployment completely removed on Apps Scripts GUI in the selected spreadsheet .

Thank you .

**Comment by sqrrrl** [comment]
Since this is already reported as a feature request on the apps script issue tracker, closing this issue.

**Comment by projektorius96** [comment]
**Citing from issue tracker:**
> Status: Won't Fix (Infeasible)
Hello there,
Thank you for reaching out and submitting this. However, since this seems to be related to the Apps Script product itself, I suggest you file this using the "Send feedback" form from the "Help" section.

Best regards

With all respect spared , let me ask @sqrrrl : "Do you really think this solves the problem by closing this?" It may be a feature request rather than problem (issue) , but running from one does not solve it , right? 🤔 I see myself in the dead end . Rather than being redirected or thankful for a feature request I was denied , how should I feel ? It's simple ignorant !
Have a nice day, Mr. Steve 💯
