### ISSUE TITLE
Bug in sample Calendar code

### ISSUE THREAD

**Issue by tcardenasc** [googleworkspace/apps-script-samples#426]
# Expected Behavior
Print the next 10 upcoming events in console.

# Actual Behavior
Only prints events until an all-day event appears.

# Solution
Change this line to `continue;`:
https://github.com/googleworkspace/apps-script-samples/blob/097b9c69514beb56cc2f080d28b3b9d7bc55eabb/advanced/calendar.gs#L120

**Comment by o23bsr0620-capke** [comment]
Thnak
