### ISSUE TITLE
How to push app scripts via github actions?

### ISSUE THREAD

**Issue by PeterLaudel** [googleworkspace/apps-script-samples#472]
# Summary

I like to push scripts via github action. 

## Expected Behavior

Sample URL: https://github.com/googleworkspace/apps-script-samples/blob/main/.github/workflows/publish.yaml
Description:

I like to push apps script via github action. I found this [example](https://github.com/googleworkspace/apps-script-samples/blob/main/.github/workflows/publish.yaml) but don't understand how the login works. What is CLASP_CREDENTIALS ans how is it generated? I tried several things like [Workload Identity Federation](https://cloud.google.com/blog/products/identity-security/enabling-keyless-authentication-from-github-actions?hl=en) or just generate a oauth key. But the problem is that there gets open a credential page or things like a 'client_id' is missing.

**Comment by vinay-google** [comment]
For clasp checkout: https://github.com/google/clasp
